---
- name: Deploy Scientific Calculator
  hosts: all
  gather_facts: no

  tasks:

    - name: Pull latest Docker image
      command: docker pull sivasomanath2502/scientific-calculator:latest

    - name: Stop existing container (if running)
      command: docker rm -f scientific-calculator
      ignore_errors: yes

    - name: Run container
      command: docker run -d -it --name scientific-calculator sivasomanath2502/scientific-calculator:latest

    - name: Check if container is running
      shell: docker ps | grep scientific-calculator
      register: container_status
      ignore_errors: yes

    - name: Fail if container not running
      fail:
        msg: "Container failed to start!"
      when: container_status.rc != 0
